<a href="https://colab.research.google.com/github/TundeRahman/Data-Wrangling-1/blob/main/M5_Forecasting_Accuracy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
calendar = pd.read_csv('calendar.csv')
calendar.sample(10)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
166,2011-07-14,11124,Thursday,6,7,2011,d_167,NaN,NaN,NaN,NaN,0,0,1
793,2013-04-01,11310,Monday,3,4,2013,d_794,NaN,NaN,NaN,NaN,1,1,0
1731,2015-10-26,11539,Monday,3,10,2015,d_1732,NaN,NaN,NaN,NaN,0,0,0
289,2011-11-14,11142,Monday,3,11,2011,d_290,NaN,NaN,NaN,NaN,0,0,1
376,2012-02-09,11202,Thursday,6,2,2012,d_377,NaN,NaN,NaN,NaN,1,1,1
856,2013-06-03,11319,Monday,3,6,2013,d_857,NaN,NaN,NaN,NaN,1,1,1
1342,2014-10-02,11435,Thursday,6,10,2014,d_1343,NaN,NaN,NaN,NaN,1,0,1
671,2012-11-30,11244,Friday,7,11,2012,d_672,NaN,NaN,NaN,NaN,0,0,0
947,2013-09-02,11332,Monday,3,9,2013,d_948,LaborDay,National,NaN,NaN,1,0,1
847,2013-05-25,11318,Saturday,1,5,2013,d_848,NaN,NaN,NaN,NaN,0,0,0

In [8]:
sales_train_evaluation = pd.read_csv('sales_train_evaluation.csv')
sales_train_evaluation

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,FOODS_3_823_WI_3_evaluation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,1,0,3,0,1,1,0,0,1,1
30486,FOODS_3_824_WI_3_evaluation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
30487,FOODS_3_825_WI_3_evaluation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,0,0,1,2,0,1,0,1,0,2
30488,FOODS_3_826_WI_3_evaluation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,1,1,4,6,0,1,1,1,0
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,2,0,5,4,0,2,2,5,1

Warning: Total number of columns (1947) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (30490) exceeds max_rows (20000). Limiting to first (20000) rows.

In [11]:
sales_train_evaluation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1947 entries, id to d_1941
dtypes: int64(1941), object(6)
memory usage: 452.9+ MB